name: Email Notification Workflow

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Pull Request: ${{ github.event.pull_request.title }}"
          to: "khadijamahmood77@yahoo.com"
          from: "noreply@example.com"
          body: |
            A new pull request has been opened in the repository:
            Repository: ${{ github.repository }}
            Action: ${{ github.event.action }}
            Author: ${{ github.actor }}
