name: Scheduled Tasks

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your maintenance tasks here
      - name: Install dependencies
        run: npm install
